- name: Watch for new events
  hosts: localhost
  sources:
    - new_events:
        instance: "{{ HCC_HOST | default('https://console.redhat.com') }}"
        proxy: "{{ HCC_PROXY | default('') }}"
        token_url: "{{ HCC_TOKEN_URL | default('https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token') }}"
        client_id: "{{ HCC_CLIENT_ID }}"
        client_secret: "{{ HCC_CLIENT_SECRET }}"
        interval: 60
  rules:
    - name: New event received
      condition: event.id is defined
      action:
        run_playbook:
          name: playbooks/new_event.yml
