---
- name: Process incoming event from Red Hat Hybrid Cloud Console
  hosts: localhost
  gather_facts: false
  vars:
    event: "{{ ansible_eda.event.payload | from_json }}"

  tasks:
    - name: Output incoming event payload
      block:
        - name: Print event data
          when: event is defined
          ansible.builtin.debug:
            msg: "Bundle: {{ event.bundle }}, Application: {{ event.application }}, Event Type: {{ event.event_type }}, Events: {{ event.events }}"
      rescue:
        - name: Print event data (wrong or unexpected schema)
          when: event is defined
          ansible.builtin.debug:
            msg: "Event: {{ event }}" 
